spring:
  datasource:
    url: jdbc:h2:mem:<DATABASE-NAME>
    driverClassName: org.h2.Driver
    username: <USERNAME FOR DB>
    password: <PASSWORD>
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: <PATH_FOR_ACCESS_CONSOLE>
      settings:
        trace: false
        web-allow-others: false
  Recolher
















